version: '3.9'

services:
        rest_service:
                build: .
                container_name: rest-service
                ports:
                        - 7654:8080
                depends_on:
                        - mysql_database
                restart: unless-stopped

        mysql_database:
                image: mysql:latest
                container_name: mysql_database
                environment:
                        - MYSQL_ROOT_PASSWORD=!Rainman1
                        - MYSQL_DATABASE=numbers
                        - MYSQL_USER=springuser
                        - MYSQL_PASSWORD=!SpringMagic1
                ports:
                        - 4567:3307
                volumes:
                        - /opt/mysql-data:/var/lib/mysql:rw
                restart: unless-stopped


